version: '3'

services:
  web:
    build: frontend/
    ports:
      - "80:80"
    links:
      - api
  
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smartmarkt
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     #- ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts downvolumes:
  
  api:
    build: backend/
    ports:
      - "8080:8080"
    links:
      - database
    depends_on: 
      - database

#volumes:
 # database-data: