
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-supermarkt
  name: ms-supermarkt
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 9000
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    app: ms-supermarkt
status:
  loadBalancer: {}
